vich_uploader:
    db_driver: orm

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
    mappings:
        shoes_images:
            uri_prefix: /images/shoes
            upload_destination: '%kernel.project_dir%/public/images/shoes'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            