controllers:
    resource: ../src/Controller/
    type: attribute
# config/routes.yaml
app_home:
    path: /home
    controller: App\Controller\HomeController::index
app_presentation_shoe:
    path: /presentation/shoe
    controller: App\Controller\PresentationShoeController::index